"""added revoked token table

Revision ID: 152312883401
Revises: 
Create Date: 2021-04-22 20:19:23.323138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152312883401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
